import java.util.ArrayList;

//Aqui se guardan los ejemplares a trabajar
public class Ejemplar{

    public Ejemplar(){}

    public static Grafica g1(){
        ArrayList<Vertice> lista = new ArrayList<Vertice>();
        Vertice v1 = new Vertice(lista, "1");
        Vertice v2 = new Vertice(lista, "2");
        Vertice v3 = new Vertice(lista, "3");
        Vertice v4 = new Vertice(lista, "4");
        Vertice v5 = new Vertice(lista, "5");
        Vertice v6 = new Vertice(lista, "6");
        Vertice v7 = new Vertice(lista, "7");
        Vertice v8 = new Vertice(lista, "8");
        Vertice v9 = new Vertice(lista, "9");
        Vertice v10 = new Vertice(lista, "10");
        Arista a1 = new Arista(v1, v2, 1);
        Arista a2 = new Arista(v1, v3, 2);
        Arista a3 = new Arista(v1, v4, 1);
        Arista a4 = new Arista(v1, v5, 2);
        Arista a5 = new Arista(v1, v6, 1);
        Arista a6 = new Arista(v1, v7, 2);
        Arista a7 = new Arista(v1, v8, 1);
        Arista a8 = new Arista(v1, v9, 2);
        Arista a9 = new Arista(v1, v10, 1);
        Arista a10 = new Arista(v2, v3, 2);
        Arista a11 = new Arista(v2, v4, 1);
        Arista a12 = new Arista(v2, v5, 2);
        Arista a13 = new Arista(v2, v6, 1);
        Arista a14 = new Arista(v2, v7, 2);
        Arista a15 = new Arista(v2, v8, 1);
        Arista a16 = new Arista(v2, v9, 2);
        Arista a17 = new Arista(v2, v10, 1);
        Arista a18 = new Arista(v3, v4, 2);
        Arista a19 = new Arista(v3, v5, 1);
        Arista a20 = new Arista(v3, v6, 2);
        Arista a21 = new Arista(v3, v7, 1);
        Arista a22 = new Arista(v3, v8, 2);
        Arista a23 = new Arista(v3, v9, 1);
        Arista a24 = new Arista(v3, v10, 2);
        Arista a25 = new Arista(v4, v5, 1);
        Arista a26 = new Arista(v4, v6, 2);
        Arista a27 = new Arista(v4, v7, 1);
        Arista a28 = new Arista(v4, v8, 2);
        Arista a29 = new Arista(v4, v9, 1);
        Arista a30 = new Arista(v4, v10, 2);
        Arista a31 = new Arista(v5, v6, 1);
        Arista a32 = new Arista(v5, v7, 2);
        Arista a33 = new Arista(v5, v8, 1);
        Arista a34 = new Arista(v5, v9, 2);
        Arista a35 = new Arista(v5, v10, 1);
        Arista a36 = new Arista(v6, v7, 2);
        Arista a37 = new Arista(v6, v8, 1);
        Arista a38 = new Arista(v6, v9, 2);
        Arista a39 = new Arista(v6, v10, 1);
        Arista a40 = new Arista(v7, v8, 2);
        Arista a41 = new Arista(v7, v9, 1);
        Arista a42 = new Arista(v7, v10, 2);
        Arista a43 = new Arista(v8, v9, 1);
        Arista a44 = new Arista(v8, v10, 2);
        Arista a45 = new Arista(v9, v10, 1);    
        ArrayList<Vertice> vertices = new ArrayList<Vertice>();
        ArrayList<Arista> aristas = new ArrayList<Arista>();
        vertices.add(v1);
        vertices.add(v2);
        vertices.add(v3);
        vertices.add(v4);
        vertices.add(v5);
        vertices.add(v6);
        vertices.add(v7);
        vertices.add(v8);
        vertices.add(v9);
        vertices.add(v10);
        aristas.add(a1);
        aristas.add(a2);
        aristas.add(a3);
        aristas.add(a4);
        aristas.add(a5);
        aristas.add(a6);
        aristas.add(a7);
        aristas.add(a8);
        aristas.add(a9);
        aristas.add(a10);
        aristas.add(a11);
        aristas.add(a12);
        aristas.add(a13);
        aristas.add(a14);
        aristas.add(a15);
        aristas.add(a16);
        aristas.add(a17);
        aristas.add(a18);
        aristas.add(a19);
        aristas.add(a20);
        aristas.add(a21);
        aristas.add(a22);
        aristas.add(a23);
        aristas.add(a24);
        aristas.add(a25);
        aristas.add(a26);
        aristas.add(a27);
        aristas.add(a28);
        aristas.add(a29);
        aristas.add(a30);
        aristas.add(a31);
        aristas.add(a32);
        aristas.add(a33);
        aristas.add(a34);
        aristas.add(a35);
        aristas.add(a36);
        aristas.add(a37);
        aristas.add(a38);
        aristas.add(a39);
        aristas.add(a40);
        aristas.add(a41);
        aristas.add(a42);
        aristas.add(a43);
        aristas.add(a44);
        aristas.add(a45);
        Grafica g = new Grafica(vertices, aristas);
        return g;
    }

    public static Grafica g2(){
        ArrayList<Vertice> lista = new ArrayList<Vertice>();
        Vertice v1 = new Vertice(lista, "1");
        Vertice v2 = new Vertice(lista, "2");
        Vertice v3 = new Vertice(lista, "3");
        Vertice v4 = new Vertice(lista, "4");
        Vertice v5 = new Vertice(lista, "5");
        Vertice v6 = new Vertice(lista, "6");
        Vertice v7 = new Vertice(lista, "7");
        Vertice v8 = new Vertice(lista, "8");
        Vertice v9 = new Vertice(lista, "9");
        Vertice v10 = new Vertice(lista, "10");
        Arista a1 = new Arista(v1, v2, 133);
        Arista a2 = new Arista(v1, v3, 135);
        Arista a3 = new Arista(v1, v4, 105);
        Arista a4 = new Arista(v1, v5, 123);
        Arista a5 = new Arista(v1, v6, 133);
        Arista a6 = new Arista(v1, v7, 125);
        Arista a7 = new Arista(v1, v8, 106);
        Arista a8 = new Arista(v1, v9, 112);
        Arista a9 = new Arista(v1, v10, 115);
        Arista a10 = new Arista(v2, v3, 124);
        Arista a11 = new Arista(v2, v4, 137);
        Arista a12 = new Arista(v2, v5, 120);
        Arista a13 = new Arista(v2, v6, 100);
        Arista a14 = new Arista(v2, v7, 122);
        Arista a15 = new Arista(v2, v8, 135);
        Arista a16 = new Arista(v2, v9, 121);
        Arista a17 = new Arista(v2, v10, 131);
        Arista a18 = new Arista(v3, v4, 125);
        Arista a19 = new Arista(v3, v5, 135);
        Arista a20 = new Arista(v3, v6, 105);
        Arista a21 = new Arista(v3, v7, 122);
        Arista a22 = new Arista(v3, v8, 123);
        Arista a23 = new Arista(v3, v9, 109);
        Arista a24 = new Arista(v3, v10, 110);
        Arista a25 = new Arista(v4, v5, 125);
        Arista a26 = new Arista(v4, v6, 101);
        Arista a27 = new Arista(v4, v7, 123);
        Arista a28 = new Arista(v4, v8, 125);
        Arista a29 = new Arista(v4, v9, 113);
        Arista a30 = new Arista(v4, v10, 112);
        Arista a31 = new Arista(v5, v6, 124);
        Arista a32 = new Arista(v5, v7, 130);
        Arista a33 = new Arista(v5, v8, 121);
        Arista a34 = new Arista(v5, v9, 132);
        Arista a35 = new Arista(v5, v10, 131);
        Arista a36 = new Arista(v6, v7, 103);
        Arista a37 = new Arista(v6, v8, 106);
        Arista a38 = new Arista(v6, v9, 131);
        Arista a39 = new Arista(v6, v10, 120);
        Arista a40 = new Arista(v7, v8, 129);
        Arista a41 = new Arista(v7, v9, 111);
        Arista a42 = new Arista(v7, v10, 110);
        Arista a43 = new Arista(v8, v9, 125);
        Arista a44 = new Arista(v8, v10, 132);
        Arista a45 = new Arista(v9, v10, 131);    
        ArrayList<Vertice> vertices = new ArrayList<Vertice>();
        ArrayList<Arista> aristas = new ArrayList<Arista>();
        vertices.add(v1);
        vertices.add(v2);
        vertices.add(v3);
        vertices.add(v4);
        vertices.add(v5);
        vertices.add(v6);
        vertices.add(v7);
        vertices.add(v8);
        vertices.add(v9);
        vertices.add(v10);
        aristas.add(a1);
        aristas.add(a2);
        aristas.add(a3);
        aristas.add(a4);
        aristas.add(a5);
        aristas.add(a6);
        aristas.add(a7);
        aristas.add(a8);
        aristas.add(a9);
        aristas.add(a10);
        aristas.add(a11);
        aristas.add(a12);
        aristas.add(a13);
        aristas.add(a14);
        aristas.add(a15);
        aristas.add(a16);
        aristas.add(a17);
        aristas.add(a18);
        aristas.add(a19);
        aristas.add(a20);
        aristas.add(a21);
        aristas.add(a22);
        aristas.add(a23);
        aristas.add(a24);
        aristas.add(a25);
        aristas.add(a26);
        aristas.add(a27);
        aristas.add(a28);
        aristas.add(a29);
        aristas.add(a30);
        aristas.add(a31);
        aristas.add(a32);
        aristas.add(a33);
        aristas.add(a34);
        aristas.add(a35);
        aristas.add(a36);
        aristas.add(a37);
        aristas.add(a38);
        aristas.add(a39);
        aristas.add(a40);
        aristas.add(a41);
        aristas.add(a42);
        aristas.add(a43);
        aristas.add(a44);
        aristas.add(a45);
        Grafica g = new Grafica(vertices, aristas);
        return g;
    }

    public static Grafica g3(){
        ArrayList<Vertice> lista = new ArrayList<Vertice>();
        Vertice v1 = new Vertice(lista, "1");
        Vertice v2 = new Vertice(lista, "2");
        Vertice v3 = new Vertice(lista, "3");
        Vertice v4 = new Vertice(lista, "4");
        Vertice v5 = new Vertice(lista, "5");
        Vertice v6 = new Vertice(lista, "6");
        Vertice v7 = new Vertice(lista, "7");
        Vertice v8 = new Vertice(lista, "8");
        Vertice v9 = new Vertice(lista, "9");
        Vertice v10 = new Vertice(lista, "10");
        Arista a1 = new Arista(v1, v2, 233);
        Arista a2 = new Arista(v1, v3, 235);
        Arista a3 = new Arista(v1, v4, 205);
        Arista a4 = new Arista(v1, v5, 223);
        Arista a5 = new Arista(v1, v6, 233);
        Arista a6 = new Arista(v1, v7, 225);
        Arista a7 = new Arista(v1, v8, 206);
        Arista a8 = new Arista(v1, v9, 212);
        Arista a9 = new Arista(v1, v10, 215);
        Arista a10 = new Arista(v2, v3, 224);
        Arista a11 = new Arista(v2, v4, 237);
        Arista a12 = new Arista(v2, v5, 220);
        Arista a13 = new Arista(v2, v6, 200);
        Arista a14 = new Arista(v2, v7, 222);
        Arista a15 = new Arista(v2, v8, 235);
        Arista a16 = new Arista(v2, v9, 221);
        Arista a17 = new Arista(v2, v10, 231);
        Arista a18 = new Arista(v3, v4, 225);
        Arista a19 = new Arista(v3, v5, 235);
        Arista a20 = new Arista(v3, v6, 205);
        Arista a21 = new Arista(v3, v7, 222);
        Arista a22 = new Arista(v3, v8, 223);
        Arista a23 = new Arista(v3, v9, 209);
        Arista a24 = new Arista(v3, v10, 210);
        Arista a25 = new Arista(v4, v5, 225);
        Arista a26 = new Arista(v4, v6, 201);
        Arista a27 = new Arista(v4, v7, 223);
        Arista a28 = new Arista(v4, v8, 225);
        Arista a29 = new Arista(v4, v9, 213);
        Arista a30 = new Arista(v4, v10, 212);
        Arista a31 = new Arista(v5, v6, 224);
        Arista a32 = new Arista(v5, v7, 230);
        Arista a33 = new Arista(v5, v8, 221);
        Arista a34 = new Arista(v5, v9, 232);
        Arista a35 = new Arista(v5, v10, 231);
        Arista a36 = new Arista(v6, v7, 203);
        Arista a37 = new Arista(v6, v8, 206);
        Arista a38 = new Arista(v6, v9, 231);
        Arista a39 = new Arista(v6, v10, 220);
        Arista a40 = new Arista(v7, v8, 229);
        Arista a41 = new Arista(v7, v9, 211);
        Arista a42 = new Arista(v7, v10, 210);
        Arista a43 = new Arista(v8, v9, 225);
        Arista a44 = new Arista(v8, v10, 232);
        Arista a45 = new Arista(v9, v10, 231);    
        ArrayList<Vertice> vertices = new ArrayList<Vertice>();
        ArrayList<Arista> aristas = new ArrayList<Arista>();
        vertices.add(v1);
        vertices.add(v2);
        vertices.add(v3);
        vertices.add(v4);
        vertices.add(v5);
        vertices.add(v6);
        vertices.add(v7);
        vertices.add(v8);
        vertices.add(v9);
        vertices.add(v10);
        aristas.add(a1);
        aristas.add(a2);
        aristas.add(a3);
        aristas.add(a4);
        aristas.add(a5);
        aristas.add(a6);
        aristas.add(a7);
        aristas.add(a8);
        aristas.add(a9);
        aristas.add(a10);
        aristas.add(a11);
        aristas.add(a12);
        aristas.add(a13);
        aristas.add(a14);
        aristas.add(a15);
        aristas.add(a16);
        aristas.add(a17);
        aristas.add(a18);
        aristas.add(a19);
        aristas.add(a20);
        aristas.add(a21);
        aristas.add(a22);
        aristas.add(a23);
        aristas.add(a24);
        aristas.add(a25);
        aristas.add(a26);
        aristas.add(a27);
        aristas.add(a28);
        aristas.add(a29);
        aristas.add(a30);
        aristas.add(a31);
        aristas.add(a32);
        aristas.add(a33);
        aristas.add(a34);
        aristas.add(a35);
        aristas.add(a36);
        aristas.add(a37);
        aristas.add(a38);
        aristas.add(a39);
        aristas.add(a40);
        aristas.add(a41);
        aristas.add(a42);
        aristas.add(a43);
        aristas.add(a44);
        aristas.add(a45);
        Grafica g = new Grafica(vertices, aristas);
        return g;
    }

    public static Grafica g4(){
        ArrayList<Vertice> lista = new ArrayList<Vertice>();
        Vertice v1 = new Vertice(lista, "1");
        Vertice v2 = new Vertice(lista, "2");
        Vertice v3 = new Vertice(lista, "3");
        Vertice v4 = new Vertice(lista, "4");
        Vertice v5 = new Vertice(lista, "5");
        Vertice v6 = new Vertice(lista, "6");
        Vertice v7 = new Vertice(lista, "7");
        Vertice v8 = new Vertice(lista, "8");
        Vertice v9 = new Vertice(lista, "9");
        Vertice v10 = new Vertice(lista, "10");
        Arista a1 = new Arista(v1, v2, 1000);
        Arista a2 = new Arista(v1, v3, 1499);
        Arista a3 = new Arista(v1, v4, 1300);
        Arista a4 = new Arista(v1, v5, 1223);
        Arista a5 = new Arista(v1, v6, 1125);
        Arista a6 = new Arista(v1, v7, 1431);
        Arista a7 = new Arista(v1, v8, 1323);
        Arista a8 = new Arista(v1, v9, 1459);
        Arista a9 = new Arista(v1, v10, 1111);
        Arista a10 = new Arista(v2, v3, 1224);
        Arista a11 = new Arista(v2, v4, 1234);
        Arista a12 = new Arista(v2, v5, 1131);
        Arista a13 = new Arista(v2, v6, 1200);
        Arista a14 = new Arista(v2, v7, 1321);
        Arista a15 = new Arista(v2, v8, 1323);
        Arista a16 = new Arista(v2, v9, 1212);
        Arista a17 = new Arista(v2, v10, 1424);
        Arista a18 = new Arista(v3, v4, 1123);
        Arista a19 = new Arista(v3, v5, 1432);
        Arista a20 = new Arista(v3, v6, 1432);
        Arista a21 = new Arista(v3, v7, 1242);
        Arista a22 = new Arista(v3, v8, 1492);
        Arista a23 = new Arista(v3, v9, 1387);
        Arista a24 = new Arista(v3, v10, 1296);
        Arista a25 = new Arista(v4, v5, 1459);
        Arista a26 = new Arista(v4, v6, 1197);
        Arista a27 = new Arista(v4, v7, 1378);
        Arista a28 = new Arista(v4, v8, 1469);
        Arista a29 = new Arista(v4, v9, 1299);
        Arista a30 = new Arista(v4, v10, 1376);
        Arista a31 = new Arista(v5, v6, 1290);
        Arista a32 = new Arista(v5, v7, 1340);
        Arista a33 = new Arista(v5, v8, 1209);
        Arista a34 = new Arista(v5, v9, 1479);
        Arista a35 = new Arista(v5, v10, 1398);
        Arista a36 = new Arista(v6, v7, 1389);
        Arista a37 = new Arista(v6, v8, 1290);
        Arista a38 = new Arista(v6, v9, 1187);
        Arista a39 = new Arista(v6, v10, 1342);
        Arista a40 = new Arista(v7, v8, 1432);
        Arista a41 = new Arista(v7, v9, 1309);
        Arista a42 = new Arista(v7, v10, 1478);
        Arista a43 = new Arista(v8, v9, 1111);
        Arista a44 = new Arista(v8, v10, 1378);
        Arista a45 = new Arista(v9, v10, 1329);    
        ArrayList<Vertice> vertices = new ArrayList<Vertice>();
        ArrayList<Arista> aristas = new ArrayList<Arista>();
        vertices.add(v1);
        vertices.add(v2);
        vertices.add(v3);
        vertices.add(v4);
        vertices.add(v5);
        vertices.add(v6);
        vertices.add(v7);
        vertices.add(v8);
        vertices.add(v9);
        vertices.add(v10);
        aristas.add(a1);
        aristas.add(a2);
        aristas.add(a3);
        aristas.add(a4);
        aristas.add(a5);
        aristas.add(a6);
        aristas.add(a7);
        aristas.add(a8);
        aristas.add(a9);
        aristas.add(a10);
        aristas.add(a11);
        aristas.add(a12);
        aristas.add(a13);
        aristas.add(a14);
        aristas.add(a15);
        aristas.add(a16);
        aristas.add(a17);
        aristas.add(a18);
        aristas.add(a19);
        aristas.add(a20);
        aristas.add(a21);
        aristas.add(a22);
        aristas.add(a23);
        aristas.add(a24);
        aristas.add(a25);
        aristas.add(a26);
        aristas.add(a27);
        aristas.add(a28);
        aristas.add(a29);
        aristas.add(a30);
        aristas.add(a31);
        aristas.add(a32);
        aristas.add(a33);
        aristas.add(a34);
        aristas.add(a35);
        aristas.add(a36);
        aristas.add(a37);
        aristas.add(a38);
        aristas.add(a39);
        aristas.add(a40);
        aristas.add(a41);
        aristas.add(a42);
        aristas.add(a43);
        aristas.add(a44);
        aristas.add(a45);
        Grafica g = new Grafica(vertices, aristas);
        return g;
    }

    public static Grafica g5(){
        ArrayList<Vertice> lista = new ArrayList<Vertice>();
        Vertice v1 = new Vertice(lista, "1");
        Vertice v2 = new Vertice(lista, "2");
        Vertice v3 = new Vertice(lista, "3");
        Vertice v4 = new Vertice(lista, "4");
        Vertice v5 = new Vertice(lista, "5");
        Vertice v6 = new Vertice(lista, "6");
        Vertice v7 = new Vertice(lista, "7");
        Vertice v8 = new Vertice(lista, "8");
        Vertice v9 = new Vertice(lista, "9");
        Vertice v10 = new Vertice(lista, "10");
        Arista a1 = new Arista(v1, v2, 1);
        Arista a2 = new Arista(v1, v3, 1);
        Arista a3 = new Arista(v1, v4, 1);
        Arista a4 = new Arista(v1, v5, 1);
        Arista a5 = new Arista(v1, v6, 1);
        Arista a6 = new Arista(v1, v7, 1);
        Arista a7 = new Arista(v1, v8, 1);
        Arista a8 = new Arista(v1, v9, 1);
        Arista a9 = new Arista(v1, v10, 1);
        Arista a10 = new Arista(v2, v3, 1);
        Arista a11 = new Arista(v2, v4, 1);
        Arista a12 = new Arista(v2, v5, 1);
        Arista a13 = new Arista(v2, v6, 1);
        Arista a14 = new Arista(v2, v7, 1);
        Arista a15 = new Arista(v2, v8, 1);
        Arista a16 = new Arista(v2, v9, 1);
        Arista a17 = new Arista(v2, v10, 1);
        Arista a18 = new Arista(v3, v4, 1);
        Arista a19 = new Arista(v3, v5, 1);
        Arista a20 = new Arista(v3, v6, 1);
        Arista a21 = new Arista(v3, v7, 1);
        Arista a22 = new Arista(v3, v8, 1);
        Arista a23 = new Arista(v3, v9, 1);
        Arista a24 = new Arista(v3, v10, 1);
        Arista a25 = new Arista(v4, v5, 1);
        Arista a26 = new Arista(v4, v6, 1);
        Arista a27 = new Arista(v4, v7, 1);
        Arista a28 = new Arista(v4, v8, 1);
        Arista a29 = new Arista(v4, v9, 1);
        Arista a30 = new Arista(v4, v10, 1);
        Arista a31 = new Arista(v5, v6, 1);
        Arista a32 = new Arista(v5, v7, 1);
        Arista a33 = new Arista(v5, v8, 1);
        Arista a34 = new Arista(v5, v9, 1);
        Arista a35 = new Arista(v5, v10, 1);
        Arista a36 = new Arista(v6, v7, 1);
        Arista a37 = new Arista(v6, v8, 1);
        Arista a38 = new Arista(v6, v9, 1);
        Arista a39 = new Arista(v6, v10, 1);
        Arista a40 = new Arista(v7, v8, 1);
        Arista a41 = new Arista(v7, v9, 1);
        Arista a42 = new Arista(v7, v10, 1);
        Arista a43 = new Arista(v8, v9, 1);
        Arista a44 = new Arista(v8, v10, 1);
        Arista a45 = new Arista(v9, v10, 1);    
        ArrayList<Vertice> vertices = new ArrayList<Vertice>();
        ArrayList<Arista> aristas = new ArrayList<Arista>();
        vertices.add(v1);
        vertices.add(v2);
        vertices.add(v3);
        vertices.add(v4);
        vertices.add(v5);
        vertices.add(v6);
        vertices.add(v7);
        vertices.add(v8);
        vertices.add(v9);
        vertices.add(v10);
        aristas.add(a1);
        aristas.add(a2);
        aristas.add(a3);
        aristas.add(a4);
        aristas.add(a5);
        aristas.add(a6);
        aristas.add(a7);
        aristas.add(a8);
        aristas.add(a9);
        aristas.add(a10);
        aristas.add(a11);
        aristas.add(a12);
        aristas.add(a13);
        aristas.add(a14);
        aristas.add(a15);
        aristas.add(a16);
        aristas.add(a17);
        aristas.add(a18);
        aristas.add(a19);
        aristas.add(a20);
        aristas.add(a21);
        aristas.add(a22);
        aristas.add(a23);
        aristas.add(a24);
        aristas.add(a25);
        aristas.add(a26);
        aristas.add(a27);
        aristas.add(a28);
        aristas.add(a29);
        aristas.add(a30);
        aristas.add(a31);
        aristas.add(a32);
        aristas.add(a33);
        aristas.add(a34);
        aristas.add(a35);
        aristas.add(a36);
        aristas.add(a37);
        aristas.add(a38);
        aristas.add(a39);
        aristas.add(a40);
        aristas.add(a41);
        aristas.add(a42);
        aristas.add(a43);
        aristas.add(a44);
        aristas.add(a45);
        Grafica g = new Grafica(vertices, aristas);
        return g;
    }
}
